version: "3"

services:
  goredis:
    container_name: "goredis"
    restart: always
    build:
      context: .
    environment:
      - BIND_PORT=6379
      - LOG_LEVEL=debug
    ports:
      - "6379:6379"

